### PR TITLE
Record slicing, take 2

### PR DESCRIPTION
**Pull request by luizirber**
Address @ctb comments in #29

### CODE REVIEW

**Comment by ctb** [comment]
Thank you, @luizirber :). I appreciate the new simplicity!

**Comment by ctb** [comment]
jenkins, ok to test

**Comment by luizirber** [comment]
- [x] Is it mergable?
- [x] Did it pass the tests?
- [x] If it introduces new functionality, is it tested?
- [x] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  and `make doc` output. Use `make format` and manual fixing as needed.
- [x] Is it documented in the ChangeLog?
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

**Comment by luizirber** [comment]
Ready for review and merge @ctb

**Comment by ctb** [comment]
LGTM.

**Pull request merged**
