### PR TITLE
Fix/760 endless screed

### PR DESCRIPTION
**Pull request by proteasome**
- [x] Is it mergable?
- [x] Did it pass the tests?
- [x] If it introduces new functionality, is it tested?
- [x] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  and `make doc` output. Use `make format` and manual fixing as needed.
- [x] Is it documented in the ChangeLog?
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
ok to test.

Note: fix for github.com/ged-lab/khmer#760.

**Comment by proteasome** [comment]
@mr-c  Only handled specific failure.  other pathalogical cases need to be checked
ready for review!

**Comment by ctb** [comment]
Please add a test!

**Comment by proteasome** [comment]
will do.  en route to boston by bus at the moment.

**Comment by luizirber** [comment]
thanks @proteasome !

**Pull request merged**
