### PR TITLE
changed default behavior of screed.open to parse_description=False

### PR DESCRIPTION
**Pull request by ctb**

### CODE REVIEW

**Comment by ctb** [comment]
Addresses https://github.com/dib-lab/khmer/issues/820

**Comment by ctb** [comment]
- [ ] Is it mergable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality, is it tested?
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  and `make doc` output. Use `make format` and manual fixing as needed.
- [ ] Is it documented in the ChangeLog?
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

Ready for review & merge, @bocajnotnef @luizirber

**Comment by luizirber** [comment]
LGTM.

**Comment by mr-c** [comment]
According to https://github.com/dib-lab/khmer/issues/820#issuecomment-76069620 this is supposed to also remove screed.description as well. Why isn't it? @ctb

**Comment by ctb** [comment]
On Mon, Jun 08, 2015 at 10:53:04AM -0700, Michael R. Crusoe wrote:
> According to https://github.com/dib-lab/khmer/issues/820#issuecomment-76069620 this is supposed to also remove screed.description as well. Why isn't it? @ctb 

Well, I forgot.  But nothing in khmer uses it, so that's ok :).  We'll
schedule it for before 1.0.

**Pull request merged**
