### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by standage**
Various cleaning tasks, many motivated by https://github.com/dib-lab/khmer/issues/864.

- normalized license / copyright claims in code files
- updated pull request template to clarify when changes to the CHANGELOG are required
- pep8 appeasement for `bigtests/*.py` and `doc/conf.py` (shoot me now)

----------

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make clean diff-cover` If it introduces new functionality, is it tested?
- [x] `make format diff_pylint_report doc` Is it well formatted?
- [x] Is it documented in the `ChangeLog`?
  http://en.wikipedia.org/wiki/Changelog#Format
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by standage** [comment]
Also, holy copy-paste Batman (in `bigtests/__init__.py`)!

**Comment by standage** [comment]
Huh, I'm baffled by this latest CI build failure.

**Comment by luizirber** [comment]
you need to test this first to avoid trying to import `pygr`:
https://github.com/dib-lab/screed/pull/57/commits/97fbef061946608f31765a03403e12a6aa5ca8ae#diff-05c883ee48c8c285338253d37d7674aeL7

**Comment by standage** [comment]
Thanks @luizirber

**Comment by standage** [comment]
Ready for review @ctb @luizirber

**Pull request merged**
